### ISSUE TITLE
Handle FITS files with extensions other than .fits

### ISSUE THREAD

**Issue by mgalloy** [astrom-tom/dfitspy#13]
I deal with many FITS files that don't use the `.fits` extension, such as `.fts` and `.FTS`, or compressed files with `.fts.gz`. Other types of FITS files, such as EIT, don't use any standard FITS extension.

**Comment by astrom-tom** [comment]
Hi @mgalloy ,

Thanks for opening the issue!
I will try to take that into account and include the different extensions. For the compressed files nonetheless would you have an file example I can work with?

**Comment by mgalloy** [comment]
Here are two examples of compressed files:

- [simple KCor L0 file](http://download.hao.ucar.edu/d5/mlso/pub/dfitspy/20190317_173313_kcor.fts.gz)
- [CoMP L1 file with extensions](http://download.hao.ucar.edu/d5/mlso/pub/dfitspy/20180101.174818.comp.1074.iv.5.fts.gz)

**Comment by astrom-tom** [comment]
@mgalloy 
Could you check with this new version (did not pushed yet on pip).
[dfitspy-19.3.4.tar.gz.zip](https://github.com/astrom-tom/dfitspy/files/2981110/dfitspy-19.3.4.tar.gz.zip)
Both FTS, fts extensions should be allowed now, as well as compressed files. 

Let me know!

**Comment by astrom-tom** [comment]
@mgalloy 

Could you try with this version? 
[dfitspy-19.3.4.tar.gz.zip](https://github.com/astrom-tom/dfitspy/files/2981435/dfitspy-19.3.4.tar.gz.zip)

FTS and fts are now supported extension, and compressed fits file (where just the data are compressed and not the header) as well

**Comment by mgalloy** [comment]
Thanks! Yes, this works for me:

    $ dfitspy -f *20????_kcor.fts.gz -key TCAMID,RCAMID,TCAMLUT,RCAMLUT

    [DFITSPY INFO]> Current directory: /export/data1/Data/KCor/raw.latest/20170910/level0 
    [DFITSPY INFO]> 165 fits files will be considered 

    filename                   	TCAMID	RCAMID	TCAMLUT       	RCAMLUT       
    ---------------------------	------	------	--------------	--------------
    20170910_200006_kcor.fts.gz	13890 	13891 	13890_20160716	13891_20160716
    20170910_200022_kcor.fts.gz	13890 	13891 	13890_20160716	13891_20160716
    20170910_200037_kcor.fts.gz	13890 	13891 	13890_20160716	13891_20160716
    20170910_200052_kcor.fts.gz	13890 	13891 	13890_20160716	13891_20160716
    ...

**Comment by astrom-tom** [comment]
Perfect! Then I will push it to pypi and update the doc.

Thanks for your input!
