### ISSUE TITLE
Provide links to dfits and fitsort docs or description

### ISSUE THREAD

**Issue by taldcroft** [astrom-tom/dfitspy#7]
Since this tool is intended to provide a Python equivalent to `dfits` and `fitsort`, it would be helpful to provide links in the `dfitspy` documentation to something describing the originals.

**Comment by astrom-tom** [comment]
Dear @taldcroft , 

I could find two links to the manpage:

ftp://134.171.42.54/scisoft/scisoft4/linux/redhat9/eclipse/eclipse/man/html1/dfits.html
ftp://134.171.42.54/scisoft/scisoft4/linux/redhat9/eclipse/eclipse/man/html1/fitsort.html

But I am really not sure about the sustainability of these links. I could not find more stable so I was thinking I could copy/paste the manpages and add them to the documentation. What do you think?

**Comment by taldcroft** [comment]
Yes, since dfitspy has a clear heritage, it would be worth it to just paste those man pages as plain (pre-formatted) text in to a separate RST doc (e.g. `dfits and fitsort man pages`) that is linked in the top Table of Contents.

**Comment by astrom-tom** [comment]
I added a separate page in the documentation with the fitsort and dfits manpage (also provided the links)
