### ISSUE TITLE
Provide some performance measure and compare with `astropy`

### ISSUE THREAD

**Issue by taldcroft** [astrom-tom/dfitspy#8]
The documentation says that dfitspy "allows you to find common values in large amount of fits files in a very fast way".

Can you provide some context for what "very fast" means?  Can you compare a grepping operation on a large list of files to doing the same with `astropy.io.fits`?  I would expect `astropy.io.fits` to be quite a bit slower given the design choices there, so it might highlight the utility of this package.

**Comment by astrom-tom** [comment]
This I will need some time because it means I have to rewrite the FITS reading  function in astropy :D.

**Comment by taldcroft** [comment]
@astrom-tom - the other way out is to just rephrase the docs as "allows you to find common values in a large number of FITS files in an efficient and convenient way".  That is definitely true: efficient because it is only reading the headers, and convenient because it manages all the low-level calls and provides a nice higher-level API.

**Comment by astrom-tom** [comment]
I rephrased as proposed.
